apiVersion: v1
kind: Service
metadata:
  name: mattermost-app
  namespace: mattermost
spec:
  selector:
    app: mattermost-app
  ports:
  - name: http
    protocol: TCP
    port: 80
  type: LoadBalancer
